### ISSUE TITLE
annotationless_perception final metrics

### ISSUE THREAD

**Issue by hayato-m126** [tier4/driving_log_replayer#453]
The NAME in diagnocstics is not always present.
It increases and decreases, so if you use metrics_score to output final_metrics, items that are not in name in the latest diag will not be output.

For example

```yaml
---
header: --
status:
- level: "\0"
  name: lateral_deviation_CAR <- not always present
---
header: --
status:
- level: "\0"
  name: yaw_deviation_CAR
```

lateral_deviation_CAR will not be output in final metrics
